### ISSUE TITLE
All images and links to dropbox are broken

### ISSUE THREAD

**Issue by Sindbag** [echen/streaming-simulations#1]
Hey, I assume information in this repo is very useful, but the most of the links are broken, so I cannot estimate that precisely.
I have got many questions about comparison bloom filters and other algos (hyperloglog, linear counter, count min sketch, etc) for cardinality estimations and this repo is one of the first results in Google search, it would be great to have that data available.

**Comment by echen** [comment]
Hi, sorry about that! Thanks for letting me know -- I fixed the links just now.
